"""
Curated list of German concert halls and opera houses for op.us.

Tiers:
  - 1: the 13 prioritised concert halls (active scraping)
  - 2: major opera houses and other concert halls (planned)
  - 3: smaller theaters and specialty venues (planned)

URLs point at calendar / programme pages.
"""
from typing import List

VENUES_GERMANY: List[dict] = [
    # Tier 1 — the 13 prioritised concert halls
    # URLs are user-curated deep-links to upcoming-events views. Some bake in a date
    # filter (Konzerthaus Berlin, Tonhalle Düsseldorf, Essen) — revisit periodically.
    {"name": "Festspielhaus Baden-Baden", "city": "Baden-Baden",
     "url": "https://www.festspielhaus.de/programm/", "tier": 1},
    {"name": "Konzerthaus Berlin", "city": "Berlin",
     "url": "https://www.konzerthaus.de/de/programm", "tier": 1},
    {"name": "Berliner Philharmonie", "city": "Berlin",
     "url": "https://www.berliner-philharmoniker.de/konzerte", "tier": 1},
    {"name": "Glocke Bremen", "city": "Bremen",
     "url": "https://www.glocke.de/tickets-programm/", "tier": 1},
    {"name": "Konzerthaus Dortmund", "city": "Dortmund",
     "url": "https://www.konzerthaus-dortmund.de/de/programm/", "tier": 1},
    {"name": "Tonhalle Düsseldorf", "city": "Düsseldorf",
     "url": "https://www.tonhalle.de/veranstaltungen/kalender", "tier": 1},
    {"name": "Philharmonie Essen", "city": "Essen",
     "url": "https://www.theater-essen.de/programm/kalender/philharmonie-essen/", "tier": 1},
    {"name": "Alte Oper Frankfurt", "city": "Frankfurt",
     "url": "https://www.alteoper.de/de/programm", "tier": 1},
    {"name": "Elbphilharmonie Hamburg", "city": "Hamburg",
     "url": "https://www.elbphilharmonie.de/de/programm/", "tier": 1},
    {"name": "Kölner Philharmonie", "city": "Köln",
     "url": "https://www.koelner-philharmonie.de/de/konzerte", "tier": 1},
    {"name": "Gewandhaus Leipzig", "city": "Leipzig",
     "url": "https://www.gewandhausorchester.de/", "tier": 1},
    {"name": "Isarphilharmonie München", "city": "München",
     "url": "https://www.mphil.de/kalender", "tier": 1},
    {"name": "Liederhalle Stuttgart", "city": "Stuttgart",
     "url": "https://liederhalle.de/eventkalender", "tier": 1},

    # Tier 2 — other major houses (opera + remaining concert halls)
    {"name": "Herkulessaal München", "city": "München",
     "url": "https://www.residenz-muenchen.de/deutsch/konzerte/", "tier": 2},
    {"name": "Staatsoper Hamburg", "city": "Hamburg",
     "url": "https://www.staatsoper-hamburg.de/de/spielplan", "tier": 2},
    {"name": "Semperoper Dresden", "city": "Dresden",
     "url": "https://www.semperoper.de/spielplan", "tier": 2},
    {"name": "Staatsoper Stuttgart", "city": "Stuttgart",
     "url": "https://www.staatsoper-stuttgart.de/spielplan", "tier": 2},
    {"name": "Bayerische Staatsoper München", "city": "München",
     "url": "https://www.staatsoper.de/spielplan", "tier": 2},
    {"name": "Deutsche Oper Berlin", "city": "Berlin",
     "url": "https://www.deutscheoperberlin.de/de_DE/calendar", "tier": 2},
    {"name": "Staatsoper Berlin", "city": "Berlin",
     "url": "https://www.staatsoper-berlin.de/de/spielplan", "tier": 2},
    {"name": "Oper Frankfurt", "city": "Frankfurt",
     "url": "https://oper-frankfurt.de/de/spielplan", "tier": 2},
    {"name": "Oper Leipzig", "city": "Leipzig",
     "url": "https://www.oper-leipzig.de/de/spielplan", "tier": 2},
    {"name": "Oper Köln", "city": "Köln",
     "url": "https://www.oper.koeln/spielplan", "tier": 2},
    {"name": "Komische Oper Berlin", "city": "Berlin",
     "url": "https://www.komische-oper-berlin.de/programm", "tier": 2},
    {"name": "Beethovenhaus Bonn", "city": "Bonn",
     "url": "https://www.beethoven.de/de/konzerte", "tier": 2},
    {"name": "Meistersingerhalle Nürnberg", "city": "Nürnberg",
     "url": "https://www.staatstheater-nuernberg.de/spielplan/konzerte", "tier": 2},
    {"name": "Prinzregententheater München", "city": "München",
     "url": "https://www.staatsoper.de/spielstaetten/prinzregententheater.html", "tier": 2},
    {"name": "Konzerthaus Freiburg", "city": "Freiburg",
     "url": "https://www.konzerthaus.freiburg.de/programm", "tier": 2},
    {"name": "Rosengarten Mannheim", "city": "Mannheim",
     "url": "https://www.rosengarten-mannheim.de/veranstaltungen", "tier": 2},
    {"name": "Konzerthaus Karlsruhe", "city": "Karlsruhe",
     "url": "https://www.staatstheater.karlsruhe.de/spielplan/konzerte", "tier": 2},
    {"name": "Stadthalle Wuppertal", "city": "Wuppertal",
     "url": "https://www.sinfonieorchester.wuppertal.de/de/konzerte", "tier": 2},
    {"name": "Stadttheater Augsburg", "city": "Augsburg",
     "url": "https://www.theater-augsburg.de/programm/konzerte", "tier": 2},
    {"name": "Staatstheater Mainz", "city": "Mainz",
     "url": "https://www.staatstheater-mainz.com/spielplan/konzerte", "tier": 2},
    {"name": "Theater Regensburg", "city": "Regensburg",
     "url": "https://www.theater-regensburg.de/programm/konzerte", "tier": 2},
    {"name": "Staatstheater Kassel", "city": "Kassel",
     "url": "https://www.staatstheater-kassel.de/programm/konzerte", "tier": 2},
    {"name": "Pierre Boulez Saal Berlin", "city": "Berlin",
     "url": "https://www.boulezsaal.de/de/kalender", "tier": 2},

    # Tier 3 — smaller theaters
    {"name": "Staatstheater Braunschweig", "city": "Braunschweig",
     "url": "https://www.staatstheater-braunschweig.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Erfurt", "city": "Erfurt",
     "url": "https://www.theater-erfurt.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Chemnitz", "city": "Chemnitz",
     "url": "https://www.theater-chemnitz.de/programm/konzerte", "tier": 3},
    {"name": "Staatstheater Oldenburg", "city": "Oldenburg",
     "url": "https://www.staatstheater-oldenburg.de/spielplan", "tier": 3},
    {"name": "Theater Kiel", "city": "Kiel",
     "url": "https://www.theater-kiel.de/programm/konzerte", "tier": 3},
    {"name": "Theater Lübeck", "city": "Lübeck",
     "url": "https://www.theater-luebeck.de/programm/konzerte", "tier": 3},
    {"name": "Staatstheater Darmstadt", "city": "Darmstadt",
     "url": "https://www.staatstheater-darmstadt.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Ulm", "city": "Ulm",
     "url": "https://www.theater.ulm.de/programm/konzerte", "tier": 3},
    {"name": "Badisches Staatstheater Karlsruhe", "city": "Karlsruhe",
     "url": "https://www.staatstheater.karlsruhe.de/spielplan", "tier": 3},
    {"name": "Staatstheater Wiesbaden", "city": "Wiesbaden",
     "url": "https://www.staatstheater-wiesbaden.de/spielplan/konzerte", "tier": 3},
    {"name": "Philharmonie Hagen", "city": "Hagen",
     "url": "https://www.theaterhagen.de/programm/konzerte", "tier": 3},
    {"name": "Stadttheater Ingolstadt", "city": "Ingolstadt",
     "url": "https://www.theater.ingolstadt.de/spielplan", "tier": 3},
    {"name": "Landestheater Coburg", "city": "Coburg",
     "url": "https://www.landestheater-coburg.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Magdeburg", "city": "Magdeburg",
     "url": "https://www.theater-magdeburg.de/programm/konzerte", "tier": 3},
    {"name": "Mecklenburgisches Staatstheater Schwerin", "city": "Schwerin",
     "url": "https://www.mecklenburgisches-staatstheater.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Hof", "city": "Hof",
     "url": "https://www.theater-hof.de/spielplan", "tier": 3},
    {"name": "Theater Heidelberg", "city": "Heidelberg",
     "url": "https://www.theaterheidelberg.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Pforzheim", "city": "Pforzheim",
     "url": "https://www.theater-pforzheim.de/spielplan/konzerte", "tier": 3},
    {"name": "Landestheater Detmold", "city": "Detmold",
     "url": "https://www.landestheater-detmold.de/spielplan/konzerte", "tier": 3},
    {"name": "Pfalztheater Kaiserslautern", "city": "Kaiserslautern",
     "url": "https://www.pfalztheater.de/spielplan/konzerte", "tier": 3},
    {"name": "Staatstheater Cottbus", "city": "Cottbus",
     "url": "https://www.staatstheater-cottbus.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Freiburg", "city": "Freiburg",
     "url": "https://www.theater.freiburg.de/spielplan/konzerte", "tier": 3},
    {"name": "Staatstheater Saarbrücken", "city": "Saarbrücken",
     "url": "https://www.staatstheater.saarland/spielplan/konzerte", "tier": 3},
    {"name": "Theater Aachen", "city": "Aachen",
     "url": "https://www.theater-aachen.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Bonn", "city": "Bonn",
     "url": "https://www.theater-bonn.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Würzburg", "city": "Würzburg",
     "url": "https://www.theaterwuerzburg.de/spielplan/konzerte", "tier": 3},
    {"name": "Anhaltisches Theater Dessau", "city": "Dessau",
     "url": "https://www.anhaltisches-theater.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Görlitz", "city": "Görlitz",
     "url": "https://www.theater-goerlitz.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Plauen-Zwickau", "city": "Plauen",
     "url": "https://www.theater-plauen-zwickau.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Vorpommern", "city": "Stralsund",
     "url": "https://www.theater-vorpommern.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Altenburg Gera", "city": "Altenburg",
     "url": "https://www.theater-altenburg-gera.de/spielplan/konzerte", "tier": 3},
    {"name": "Stadttheater Hildesheim", "city": "Hildesheim",
     "url": "https://www.theaterhildesheim.de/spielplan/konzerte", "tier": 3},
    {"name": "Theater Trier", "city": "Trier",
     "url": "https://www.theater-trier.de/spielplan/konzerte", "tier": 3},
    {"name": "Stadttheater Gießen", "city": "Gießen",
     "url": "https://www.stadttheater-giessen.de/spielplan/konzerte", "tier": 3},
    {"name": "Theaterkonstanz", "city": "Konstanz",
     "url": "https://www.theaterkonstanz.de/spielplan/konzerte", "tier": 3},
    {"name": "Konzerthaus Blaibach", "city": "Blaibach",
     "url": "https://www.konzerthaus-blaibach.de/konzerte", "tier": 3},
]


def get_all_venues() -> List[dict]:
    return VENUES_GERMANY


def get_venues_by_tier(tier) -> List[dict]:
    return [v for v in VENUES_GERMANY if v["tier"] == tier]


def get_venues_by_city(city: str) -> List[dict]:
    return [v for v in VENUES_GERMANY if v["city"].lower() == city.lower()]
